module.exports = {
    // Main server command
    serverDescription: "Comprehensive server information and management commands",
    
    // Subcommand descriptions
    serverInfoDescription: "Hiển thị thông tin chi tiết về máy chủ với phân trang nâng cao",
    serverIconDescription: "Hiển thị biểu tượng máy chủ với chất lượng cao",
    serverBannerDescription: "Hiển thị banner của máy chủ nếu có",
    serverMembercountDescription: "Thống kê và phân tích số lượng thành viên chi tiết",
    serverRolesDescription: "Danh sách đầy đủ các vai trò trong máy chủ kèm chi tiết",
    serverEmojisDescription: "Hiển thị tất cả biểu tượng cảm xúc của máy chủ theo từng nhóm",
    serverChannelsDescription: "Tổng quan và thống kê đầy đủ về các kênh",
    serverBoostsDescription: "Thông tin về số lượng boost và các đặc quyền của máy chủ",
    serverRegionDescription: "Thông tin khu vực và ngôn ngữ của máy chủ",
    serverVerificationDescription: "Chi tiết về mức độ xác minh hiện tại của máy chủ",
    serverFeaturesDescription: "Tất cả các tính năng và khả năng đã được bật trong máy chủ",


    // Error messages
    serverErrorTitle: "❌ **LỖI**",
    serverErrorColor: "#ff4757",
    serverErrorDescription: "``````",
    serverInfoErrorDescription: "``````",

    // Colors
    serverInfoColor: "#00d4ff",
    serverIconColor: "#7c3aed",
    serverIconNoIconColor: "#ff6b6b",
    serverBannerColor: "#00d4ff",
    serverBannerNoBannerColor: "#ff6b6b",
    serverMembercountColor: "#00bfff",
    serverRolesColor: "#8e44ad",
    serverEmojisColor: "#f39c12",
    serverChannelsColor: "#2ecc71",
    serverBoostsColor: "#ff73fa",
    serverRegionColor: "#95a5a6",
    serverVerificationColor: "#3498db",
    serverFeaturesColor: "#3498db",
    serverHelpColor: "#7289da",

    // Server Info command - 
    serverInfoTitle: "🏰 **Thông Tin Server**",
    serverInfoEmbedDescription: `\`\`\`\n🏰 SERVER ANALYTICS DASHBOARD\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverInfoNameField: "📛 **Tên Máy Chủ**",
    serverInfoNameValue: "🏷️ Danh tính",
    serverInfoOwnerField: "👑 **Chủ Sở Hữu**",
    serverInfoOwnerValue: "🎯 Quản trị viên",
    serverInfoIdField: "🆔 **ID Máy Chủ**",
    serverInfoIdValue: "🔢 Duy nhất",
    serverInfoMembersField: "👥 **Tổng Thành Viên**",
    serverInfoMembersValue: "📈 Cộng đồng",
    serverInfoBotsField: "🤖 **Số Lượng Bot**",
    serverInfoBotsValue: "🔧 Tự động hóa",
    serverInfoBoostField: "🚀 **Trạng Thái Boost**",
    serverInfoBoostText: "Số lượt Boost",
    serverInfoLevelText: "Cấp độ",
    serverInfoTierText: "Hạng",
    serverInfoCategoriesField: "📂 **Danh Mục**",
    serverInfoCategoriesValue: "📊 Tổ chức",
    serverInfoTextField: "💬 **Kênh Văn Bản**",
    serverInfoTextValue: "📝 Giao tiếp",
    serverInfoVoiceField: "🔊 **Kênh Thoại**",
    serverInfoVoiceValue: "🎤 Âm thanh",
    serverInfoRolesField: "🎭 **Tổng Vai Trò**",
    serverInfoRolesValue: "🛡️ Thứ bậc",
    serverInfoEmojisField: "😀 **Biểu Cảm Tuỳ Chỉnh**",
    serverInfoEmojisValue: "🎨 Biểu đạt",
    serverInfoCreatedField: "🆕 **Ngày Tạo Máy Chủ**",
    serverInfoFooter: "📊 Trang {page} trên {total} • Phân tích nâng cao",
    serverInfoPreviousButton: "◀️ Trước",
    serverInfoNextButton: "Tiếp ▶️",

    // Server Icon command - Lệnh biểu tượng máy chủ
    serverIconTitle: "🖼️ **BIỂU TƯỢNG MÁY CHỦ**",
    serverIconEmbedDescription: `\`\`\`\n🖼️ BỘ SƯU TẬP ICON\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n🏰 **{serverName}**\n\n🔗 **[Tải ảnh gốc]({iconURL})**\n\n\`\`\`yaml\nChi Tiết Hình Ảnh:\n  Định dạng: PNG chất lượng cao\n  Độ phân giải: 1024x1024\n  Loại: {imageType}\n\`\`\``,
    serverIconNoIconDescription: `\`\`\`\n🖼️ HIỂN THỊ ICON\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n❌ **Không tìm thấy biểu tượng máy chủ**\n\n\`\`\`yaml\Gợi ý:\n  Tải lên biểu tượng trong Cài Đặt Máy Chủ\n  Kích thước khuyên dùng: 512x512 pixels\n   Định dạng hỗ trợ: PNG, JPG, GIF\n\`\`\``,
    serverIconAnimated: "Động",
    serverIconStatic: "Tĩnh",
    serverIconFooter: "🎨 Biểu tượng máy chủ • {memberCount} thành viên",

    // Server Banner command
    serverBannerTitle: "🎨 **BANNER MÁY CHỦ**",
    serverBannerEmbedDescription: `\`\`\`\n🎨 TRÌNH DIỄN BANNER\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n🏰 **{serverName}**\n\n🔗 **[Tải ảnh gốc]({bannerURL})**\n\n\`\`\`yaml\nChi Tiết Banner:\n  Định dạng: PNG chất lượng cao\n  Độ phân giải: 1920x1080\n  Cấp độ Boost: {boostLevel}\n  Trạng thái: Tính năng cao cấp\n\`\`\``,
    serverBannerNoBannerDescription: `\`\`\`\n🎨 HIỂN THỊ BANNER\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n❌ **Không tìm thấy banner máy chủ**\n\n\`\`\`yaml\nYêu cầu:\n  Cấp độ Boost: Cần đạt cấp 2 trở lên\n  Cấp hiện tại: {currentLevel}\n  Số boost còn thiếu: {neededBoosts}\n\`\`\`\n\n> 🚀 **Hãy boost máy chủ này để mở khóa banner!**`,
    serverBannerFooter: "🎨 Banner Máy Chủ • Đã Boost cấp {boostLevel}",

    // Server Membercount command - Lệnh đếm và phân tích thành viên máy chủ
    serverMembercountTitle: "👥 **PHÂN TÍCH THÀNH VIÊN**",
    serverMembercountEmbedDescription: `\`\`\`\n👥 THỐNG KÊ CỘNG ĐỒNG\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverMembercountTotalField: "📊 **Tổng Số Thành Viên**",
    serverMembercountTotalValue: "🌐 Cộng đồng",
    serverMembercountHumansField: "👤 **Người Dùng Thật**",
    serverMembercountHumansValue: "🧑‍🤝‍🧑 Con người thật",
    serverMembercountBotsField: "🤖 **Người Dùng Bot**",
    serverMembercountBotsValue: "⚙️ Tự động hóa",
    serverMembercountOnlineField: "🟢 **Đang Hoạt Động**",
    serverMembercountOnlineValue: "✅ Đang hoạt động",
    serverMembercountIdleField: "🌙 **Rảnh Rỗi**",
    serverMembercountIdleValue: "⏰ Vắng mặt",
    serverMembercountDndField: "🔴 **Không Làm Phiền**",
    serverMembercountDndValue: "🚫 Bận",
    serverMembercountOfflineField: "⚪ **Ngoại Tuyến**",
    serverMembercountOfflineValue: "💤 Không hoạt động",
    serverMembercountFooter: "📈 Phân Tích Thành Viên • {percentage}% là người thật",

    // Server Roles command
    serverRolesTitle: "🎭 **THỨ BẬC VAI TRÒ**",
    serverRolesEmbedDescription: `\`\`\`\n🎭 CẤU TRÚC PHÂN QUYỀN\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverRolesMembersText: "thành viên",
    serverRolesNoneFound: "`Không tìm thấy vai trò tùy chỉnh nào`",
    serverRolesStats: `\`\`\`yaml\nThống Kê:\n  Tổng số vai trò: {total}\n  Vai trò cao nhất: {highest}\n  Vai trò có nhiều thành viên nhất: {mostMembers}\n\`\`\``,
    serverRolesNone: "Không có",
    serverRolesFooter: "🎭 Trang {page} trên {total} • Quản lý vai trò",
    
    // Server Roles Management
    serverRolesManagementTitle: "🎭 **QUẢN LÝ VAI TRÒ** [{count}]",
    serverRolesManagementDescription: `\`\`\`\n🎭 HỆ THỐNG THỨ BẬC\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverRolesListMembersText: "thành viên",
    serverRolesManagementStats: `\`\`\`yaml\nThống Kê Vai Trò:\n  Tổng số vai trò: {total}\n  Vai trò hiển thị riêng: {hoisted}\n  Có thể nhắc đến: {mentionable}\n  Có quyền hạn: {withPermissions}\n\`\`\``,
    serverRolesManagementFooter: "🎭 Thứ bậc Vai Trò • Tổng cộng {count} vai trò",

    // Server Emojis command
    serverEmojisTitle: "😀 **BỘ SƯU TẬP EMOJI** ({current}/{total})",
    serverEmojisEmbedDescription: `\`\`\`\n😀 THƯ VIỆN EMOJI\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverEmojisStats: `\`\`\`yaml\nThống Kê Bộ Sưu Tập:\n  Tổng số Emoji: {total}\n  Động: {animated}\n  Tĩnh: {static}\n  Trang: {currentPage}/{totalPages}\n\`\`\``,
    serverEmojisFooter: "😀 Trang {page} trên {total} • Trình Quản Lý Emoji",

    // Server Emojis Collection
    serverEmojisCollectionTitle: "😀 **BỘ SƯU TẬP EMOJI**",
    serverEmojisCollectionDescription: `\`\`\`\n😀 THƯ VIỆN EMOJI\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverEmojisAnimatedField: "🎞️ **Emoji Động**",
    serverEmojisStaticField: "🖼️ **Emoji Tĩnh**",
    serverEmojisNone: "Không có",
    serverEmojisNoAnimated: "`Không có emoji động`",
    serverEmojisNoStatic: "`Không có emoji tĩnh`",
    serverEmojisCollectionFooter: "😀 Bộ Sưu Tập Emoji • Tổng {total} ({animated} emoji động, {static} emoji tĩnh)",

    // Server Channels command
    serverChannelsTitle: "📚 **TỔNG QUAN KÊNH**",
    serverChannelsEmbedDescription: `\`\`\`\n📚 CƠ CẤU KÊNH\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverChannelsCategoriesField: "📂 **Danh mục**",
    serverChannelsCategoriesValue: "🗂️ Tổ chức",
    serverChannelsTextField: "💬 **Kênh văn bản**",
    serverChannelsTextValue: "📝 Thảo luận",
    serverChannelsVoiceField: "🔊 **Kênh thoại**",
    serverChannelsVoiceValue: "🎤 Trò chuyện âm thanh",
    serverChannelsStageField: "🎭 **Kênh sân khấu**",
    serverChannelsStageValue: "🎪 Trình bày",
    serverChannelsThreadsField: "🧵 **Chủ đề hoạt động**",
    serverChannelsThreadsValue: "💭 Thảo luận",
    serverChannelsNewsField: "📰 **Kênh tin tức**",
    serverChannelsNewsValue: "📢 Thông báo",
    serverChannelsForumField: "🏛️ **Kênh diễn đàn**",
    serverChannelsForumValue: "💬 Hỏi & Đáp",
    serverChannelsFooter: "📚 Hệ thống kênh • Tổng {total} kênh",

    // Server Boosts command
    serverBoostsTitle: "🚀 **PHÂN TÍCH BOOST**",
    serverBoostsEmbedDescription: `\`\`\`\n🚀 BẢNG ĐIỀU KHIỂN BOOST\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverBoostsCurrentField: "💎 **Cấp Hiện Tại**",
    serverBoostsActiveField: "🚀 **Số Lượng Boost Đang Hoạt Động**",
    serverBoostsActiveValue: "💝 Người Ủng Hộ",
    serverBoostsNextField: "📈 **Cấp Tiếp Theo**",
    serverBoostsMoreNeeded: "cần thêm",
    serverBoostsTarget: "🎯 Mục Tiêu",
    serverBoostsMaxLevel: "`Đã đạt cấp tối đa`\n🏆 Trạng thái ưu tú",
    serverBoostsPerksField: "🎁 **Phần Thưởng Cấp {level}**",
    serverBoostsThumbnail: "https://cdn.discordapp.com/emojis/853314249405071390.gif",
    serverBoostsFooter: "🚀 Hệ Thống Boost • Tìm hiểu thêm: discord.com/nitro",

    // Boost perks by level
    serverBoostPerks: {
        0: ["📱 Phát trực tiếp trên điện thoại", "🎧 Chất lượng âm thanh: 96kbps"],
        1: ["🎬 Chia sẻ màn hình: 720p 60fps", "📊 Emoji tùy chỉnh: tổng 50", "🎧 Chất lượng âm thanh: 128kbps"],
        2: ["🎬 Chia sẻ màn hình: 1080p 60fps", "📊 Emoji tùy chỉnh: tổng 100", "🎨 Banner máy chủ", "📁 Giới hạn tải lên: 50MB"],
        3: ["🎬 Chia sẻ màn hình: 4K 60fps", "📊 Emoji tùy chỉnh: tổng 250", "🎨 Icon máy chủ động", "📁 Giới hạn tải lên: 100MB", "🎵 Nền mời tùy chỉnh"]
    },

    // Server Region command
    serverRegionTitle: "🌍 **KHU VỰC MÁY CHỦ**",
    serverRegionEmbedDescription: `\`\`\`\n🌍 CÀI ĐẶT KHU VỰC\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\`\n\n🗺️ **Ngôn ngữ Ưa thích:** \`{locale}\`\n\n\`\`\`yaml\nLợi ích Khu Vực:\n  🌐 Kết nối tối ưu\n  📊 Tính năng địa phương hóa\n  🎯 Nội dung hướng mục tiêu\n  ⚡ Giảm độ trễ\n\`\`\`\n\n> 🔧 **Quản trị viên có thể thay đổi trong Cài đặt Máy chủ**`,
    serverRegionFooter: "🌍 Khu vực máy chủ • {memberCount} thành viên toàn cầu",
    serverRegionDefaultLocale: "Tiếng Anh (Mỹ)",

    // Server Verification command
    serverVerificationTitle: "🔐 **HỆ THỐNG XÁC THỰC**",
    serverVerificationEmbedDescription: `\`\`\`\n🔐 BẢNG ĐIỀU KHIỂN BẢO MẬT\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverVerificationCurrentField: "🛡️ **Cấp Hiện Tại**",
    serverVerificationRequirementsField: "📋 **Yêu Cầu**",
    serverVerificationProtectionField: "🎯 **Bảo Vệ**",
    serverVerificationLevelsField: "📊 **Các Cấp Xác Thực**",
    serverVerificationSecurityText: "🔧 Bảo mật",
    serverVerificationActiveText: "✅ Đang hoạt động",
    serverVerificationEnhancedText: "Bảo mật nâng cao",
    serverVerificationNoRestrictions: "Không giới hạn",
    serverVerificationEmailVerification: "Xác thực email",
    serverVerificationAccountAge: "Yêu cầu tuổi tài khoản",
    serverVerificationMemberDuration: "Yêu cầu thời gian làm thành viên",
    serverVerificationPhoneVerification: "Xác thực điện thoại",
    serverVerificationFooter: "🔐 Hệ thống xác thực • Cấp {level} đang hoạt động",

    // Verification levels
        serverVerificationLevels: {
        0: { name: "Không", desc: "Không yêu cầu xác thực", emoji: "🔓", color: "#95a5a6" },
        1: { name: "Thấp", desc: "Yêu cầu xác thực email", emoji: "📧", color: "#3498db" },
        2: { name: "Trung bình", desc: "Tuổi tài khoản > 5 phút", emoji: "⏰", color: "#f39c12" },
        3: { name: "Cao", desc: "Làm thành viên trên 10 phút", emoji: "🔒", color: "#e74c3c" },
        4: { name: "Rất cao", desc: "Yêu cầu số điện thoại", emoji: "📱", color: "#8e44ad" }
    },

    // Server Features command
    serverFeaturesTitle: "🛠️ **TÍNH NĂNG MÁY CHỦ**",
    serverFeaturesEmbedDescription: `\`\`\`\n🛠️ BẢNG ĐIỀU KHIỂN TÍNH NĂNG\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverFeaturesEnabledField: "🎯 **Tính năng đang bật**",
    serverFeaturesNoneEnabled: "`Không có tính năng đặc biệt nào được bật`",
    serverFeaturesCountField: "📊 **Số lượng tính năng**",
    serverFeaturesCountValue: "🔧 Tổng số tính năng",
    serverFeaturesCustomizationField: "🎨 **Tùy chỉnh**",
    serverFeaturesCustomizationValue: "🖌️ Tính năng hình ảnh",
    serverFeaturesSecurityField: "🛡️ **Bảo mật**",
    serverFeaturesSecurityValue: "🔒 Tính năng an toàn",
    serverFeaturesFooter: "🛠️ Tính năng máy chủ • {count} tính năng đang hoạt động",

    // Feature descriptions
    serverFeatureDescriptions: {
        'ANIMATED_BANNER': '🎬 Banner động',
        'ANIMATED_ICON': '🎭 Icon động',
        'APPLICATION_COMMAND_PERMISSIONS_V2': '⚙️ Quyền nâng cao',
        'AUTO_MODERATION': '🤖 Tự động quản lý',
        'BANNER': '🎨 Banner máy chủ',
        'COMMUNITY': '🌐 Máy chủ cộng đồng',
        'DEVELOPER_SUPPORT_SERVER': '👨‍💻 Hỗ trợ nhà phát triển',
        'DISCOVERABLE': '🔍 Tìm kiếm máy chủ',
        'FEATURABLE': '⭐ Có thể giới thiệu',
        'INVITES_DISABLED': '🚫 Tắt lời mời',
        'INVITE_SPLASH': '🌊 Màn hình mời',
        'MEMBER_VERIFICATION_GATE_ENABLED': '🔐 Kiểm duyệt thành viên',
        'MORE_EMOJI': '😀 Mở rộng emoji',
        'NEWS': '📰 Kênh tin tức',
        'PARTNERED': '🤝 Đối tác Discord',
        'PREVIEW_ENABLED': '👁️ Xem trước máy chủ',
        'PRIVATE_THREADS': '🧵 Chủ đề riêng tư',
        'ROLE_ICONS': '🎭 Icon vai trò',
        'THREADS_ENABLED': '💬 Chủ đề được bật',
        'THREE_DAY_THREAD_ARCHIVE': '📦 Lưu trữ chủ đề 3 ngày',
        'TICKETED_EVENTS_ENABLED': '🎟️ Sự kiện vé',
        'VANITY_URL': '🔗 URL tùy chỉnh',
        'VERIFIED': '✅ Máy chủ đã xác minh',
        'VIP_REGIONS': '🌍 Khu vực thoại VIP',
        'WELCOME_SCREEN_ENABLED': '👋 Màn hình chào mừng'
    },

    // Server Help command
    serverHelpTitle: "🏰 **HƯỚNG DẪN LỆNH MÁY CHỦ**",
    serverHelpEmbedDescription: `\`\`\`\n🏰 ĐIỀU HƯỚNG LỆNH\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\`\`\``,
    serverHelpInformationField: "📊 **Thông tin**",
    serverHelpInformationValue: "`/server info` - Tổng quan chi tiết máy chủ\n`/server membercount` - Phân tích thành viên\n`/server verification` - Cài đặt bảo mật",
    serverHelpVisualField: "🎨 **Hình ảnh**",
    serverHelpVisualValue: "`/server icon` - Hiển thị biểu tượng máy chủ\n`/server banner` - Xem banner máy chủ\n`/server emojis` - Bộ sưu tập emoji",
    serverHelpManagementField: "⚙️ **Quản lý**",
    serverHelpManagementValue: "`/server roles` - Hệ thống vai trò\n`/server channels` - Tổng quan kênh\n`/server features` - Khả năng máy chủ",
    serverHelpPremiumField: "🚀 **Premium**",
    serverHelpPremiumValue: "`/server boosts` - Thông tin Boost\n`/server region` - Khu vực máy chủ\n`/server features` - Tính năng cao cấp",
    serverHelpFooter: "🏰 Công cụ máy chủ • {serverName}",
};
